        Workbook to figure out how to specify source positions (a) in an array in order to graph error

In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [26]:
# Set up x, y and z for positions of a (sound source)
x = np.linspace(0, 20, 21).reshape(-1, 1)
y = np.zeros_like(x)
z = np.zeros_like(x)

# Create an (number_points x 3) array of the 'a' positions
a = np.concatenate((x, y, z), axis=1)
H = np.array([[0,0,0],[20, 0, 0]],dtype=float)

In [37]:
# Setting up the points in the x-y plane
x = np.linspace(0,20,21)
y = np.linspace(0,20,21)
X, Y = np.meshgrid(x,y,indexing='xy')
Y = Y.reshape(-1,1)
X = X.reshape(-1,1)
Z = np.zeros_like(X)


a = np.concatenate((X, Y, Z), axis=1)
a

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 2.,  0.,  0.],
       ...,
       [18., 20.,  0.],
       [19., 20.,  0.],
       [20., 20.,  0.]])

In [33]:
def distance_multimic(a, H):
    """

    :param a: 1 x 3 array
    :param H: i x 3 array
    :return: 1 x i array of distance values
    """
    out = np.zeros((a.shape[0], H.shape[0]))
    
    for i in range(H.shape[0]):
        out[:, i] = np.sqrt(np.sum(np.square(H[i, :] - a), axis=1))
    return out

In [44]:
dist = distance_multimic(a,H)
dist[:,0].reshape(21,-1)

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
         5.        ,  6.        ,  7.        ,  8.        ,  9.        ,
        10.        , 11.        , 12.        , 13.        , 14.        ,
        15.        , 16.        , 17.        , 18.        , 19.        ,
        20.        ],
       [ 1.        ,  1.41421356,  2.23606798,  3.16227766,  4.12310563,
         5.09901951,  6.08276253,  7.07106781,  8.06225775,  9.05538514,
        10.04987562, 11.04536102, 12.04159458, 13.03840481, 14.03566885,
        15.03329638, 16.03121954, 17.02938637, 18.02775638, 19.02629759,
        20.02498439],
       [ 2.        ,  2.23606798,  2.82842712,  3.60555128,  4.47213595,
         5.38516481,  6.32455532,  7.28010989,  8.24621125,  9.21954446,
        10.19803903, 11.18033989, 12.16552506, 13.15294644, 14.14213562,
        15.13274595, 16.1245155 , 17.11724277, 18.11077028, 19.10497317,
        20.09975124],
       [ 3.        ,  3.16227766,  3.60555128,  4.24264069

What is happening above is that we are changing the meshgrid into a 1D array so that we can do calculations on it easily. Then when we have calculated what we want through the distance calculations, we SHOULD be able to just reshape back to our meshgrid to obtain Z.

In [47]:
range_points = 60
number_points = 200
a=np.concatenate((np.linspace(0, range_points, number_points).reshape(-1, 1),np.zeros((number_points,1)),np.zeros((number_points,1))), axis=1)
a

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.30150754,  0.        ,  0.        ],
       [ 0.60301508,  0.        ,  0.        ],
       [ 0.90452261,  0.        ,  0.        ],
       [ 1.20603015,  0.        ,  0.        ],
       [ 1.50753769,  0.        ,  0.        ],
       [ 1.80904523,  0.        ,  0.        ],
       [ 2.11055276,  0.        ,  0.        ],
       [ 2.4120603 ,  0.        ,  0.        ],
       [ 2.71356784,  0.        ,  0.        ],
       [ 3.01507538,  0.        ,  0.        ],
       [ 3.31658291,  0.        ,  0.        ],
       [ 3.61809045,  0.        ,  0.        ],
       [ 3.91959799,  0.        ,  0.        ],
       [ 4.22110553,  0.        ,  0.        ],
       [ 4.52261307,  0.        ,  0.        ],
       [ 4.8241206 ,  0.        ,  0.        ],
       [ 5.12562814,  0.        ,  0.        ],
       [ 5.42713568,  0.        ,  0.        ],
       [ 5.72864322,  0.        ,  0.        ],
       [ 6.03015075,  0.        ,  0.   

In [48]:
np.delete(a, -1 , 1)

array([[ 0.        ,  0.        ],
       [ 0.30150754,  0.        ],
       [ 0.60301508,  0.        ],
       [ 0.90452261,  0.        ],
       [ 1.20603015,  0.        ],
       [ 1.50753769,  0.        ],
       [ 1.80904523,  0.        ],
       [ 2.11055276,  0.        ],
       [ 2.4120603 ,  0.        ],
       [ 2.71356784,  0.        ],
       [ 3.01507538,  0.        ],
       [ 3.31658291,  0.        ],
       [ 3.61809045,  0.        ],
       [ 3.91959799,  0.        ],
       [ 4.22110553,  0.        ],
       [ 4.52261307,  0.        ],
       [ 4.8241206 ,  0.        ],
       [ 5.12562814,  0.        ],
       [ 5.42713568,  0.        ],
       [ 5.72864322,  0.        ],
       [ 6.03015075,  0.        ],
       [ 6.33165829,  0.        ],
       [ 6.63316583,  0.        ],
       [ 6.93467337,  0.        ],
       [ 7.2361809 ,  0.        ],
       [ 7.53768844,  0.        ],
       [ 7.83919598,  0.        ],
       [ 8.14070352,  0.        ],
       [ 8.44221106,